-- migrations/catalog-schema.sql — post-migration snapshot.
--
-- Auto-generated by `npm run db:dump-schema` from a fresh
-- in-memory apply of every migration under migrations/catalog/.
-- CI runs the migrations smoke test and fails the PR if the
-- generated output drifts from this file.
--
-- Do not edit by hand. Edit the migration file in
-- migrations/catalog/ and regenerate.

-- Tables

CREATE TABLE asset_uploads (
  id              TEXT PRIMARY KEY,           -- ULID
  dataset_id      TEXT NOT NULL,
  publisher_id    TEXT NOT NULL,              -- who minted the URL
  kind            TEXT NOT NULL,              -- data | thumbnail | legend | caption | sphere_thumbnail
  target          TEXT NOT NULL,              -- r2 | stream
  target_ref      TEXT NOT NULL,              -- r2:<key> | stream:<uid>
  mime            TEXT NOT NULL,
  declared_size   INTEGER NOT NULL,
  claimed_digest  TEXT NOT NULL,              -- "sha256:<hex>"
  status          TEXT NOT NULL,              -- pending | completed | failed
  failure_reason  TEXT,                       -- machine-readable code; NULL when status != failed
  created_at      TEXT NOT NULL,
  completed_at    TEXT,                       -- stamped on completed | failed
  FOREIGN KEY (dataset_id)   REFERENCES datasets(id) ON DELETE CASCADE,
  FOREIGN KEY (publisher_id) REFERENCES publishers(id)
);

CREATE TABLE audit_events (
  id              TEXT PRIMARY KEY,           -- ULID
  actor_kind      TEXT NOT NULL,              -- publisher | peer | system
  actor_id        TEXT,
  action          TEXT NOT NULL,
  subject_kind   TEXT NOT NULL,               -- dataset | tour | peer | grant
  subject_id     TEXT,
  metadata_json  TEXT,
  created_at     TEXT NOT NULL
);

CREATE TABLE dataset_categories (
  dataset_id  TEXT NOT NULL,
  facet       TEXT NOT NULL,                  -- e.g., "Theme", "Region"
  value       TEXT NOT NULL,
  PRIMARY KEY (dataset_id, facet, value),
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE TABLE dataset_developers (
  dataset_id      TEXT NOT NULL,
  role            TEXT NOT NULL,              -- 'data' | 'visualization'
  name            TEXT NOT NULL,
  affiliation_url TEXT,
  PRIMARY KEY (dataset_id, role, name),
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE TABLE dataset_keywords (
  dataset_id  TEXT NOT NULL,
  keyword     TEXT NOT NULL,
  PRIMARY KEY (dataset_id, keyword),
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE TABLE dataset_related (
  dataset_id     TEXT NOT NULL,
  related_title  TEXT NOT NULL,
  related_url    TEXT NOT NULL,
  PRIMARY KEY (dataset_id, related_url),
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE TABLE dataset_renditions (
  dataset_id     TEXT NOT NULL,
  rendition_id   TEXT NOT NULL,               -- ULID
  codec          TEXT NOT NULL,               -- h264 | hevc | vp9 | av1
  color_space    TEXT NOT NULL,
  bit_depth      INTEGER NOT NULL,
  has_alpha      INTEGER NOT NULL DEFAULT 0,
  alpha_encoding TEXT,
  width          INTEGER NOT NULL,            -- encoded width
  height         INTEGER NOT NULL,            -- encoded height
  bitrate_kbps   INTEGER,
  ref            TEXT NOT NULL,               -- stream:<uid>/profile or r2-hls:<key>
  mime_type      TEXT NOT NULL,
  content_digest TEXT,                        -- "sha256:<hex>" of the rendition's master playlist
  created_at     TEXT NOT NULL,
  PRIMARY KEY (dataset_id, rendition_id),
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE TABLE dataset_tags (
  dataset_id  TEXT NOT NULL,
  tag         TEXT NOT NULL,
  PRIMARY KEY (dataset_id, tag),
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE
);

CREATE TABLE datasets (
  id                 TEXT PRIMARY KEY,        -- ULID
  slug               TEXT NOT NULL UNIQUE,
  origin_node        TEXT NOT NULL,           -- always = node_identity.node_id for own rows
  title              TEXT NOT NULL,
  abstract           TEXT,
  organization       TEXT,
  format             TEXT NOT NULL,           -- video/mp4, image/png, tour/json, ...
  data_ref           TEXT NOT NULL,           -- stream:<uid> | r2:<key> | vimeo:<id> | url:<url> | peer:<node_id>/<id>

  -- Asset integrity (Phase 1b populates).
  content_digest     TEXT,
  source_digest      TEXT,
  auxiliary_digests  TEXT,                    -- JSON: { "thumbnail": "sha256:...", ... }

  thumbnail_ref           TEXT,
  sphere_thumbnail_ref    TEXT,
  sphere_thumbnail_ref_lg TEXT,
  legend_ref         TEXT,
  caption_ref        TEXT,
  website_link       TEXT,
  start_time         TEXT,                    -- ISO 8601
  end_time           TEXT,
  period             TEXT,                    -- ISO 8601 duration
  weight             INTEGER NOT NULL DEFAULT 0,
  visibility         TEXT NOT NULL DEFAULT 'public',
                                              -- public | federated | restricted | private
  is_hidden          INTEGER NOT NULL DEFAULT 0,
  run_tour_on_load   TEXT,

  -- Media intrinsics (Phase 1b populates).
  width              INTEGER,
  height             INTEGER,
  render_width       INTEGER,
  render_height      INTEGER,
  color_space        TEXT,                    -- rec709 | rec2020-pq | rec2020-hlg | p3 | srgb
  bit_depth          INTEGER,                 -- 8 | 10 | 12
  hdr_transfer       TEXT,                    -- null | pq | hlg
  has_alpha          INTEGER NOT NULL DEFAULT 0,
  alpha_encoding     TEXT,                    -- null | native_vp9 | native_hevc | packed_below | packed_right
  primary_codec      TEXT,                    -- h264 | hevc | vp9 | av1 (informational)

  -- License & attribution (Phase 1a populates from seeded SOS data).
  license_spdx       TEXT,
  license_url        TEXT,
  license_statement  TEXT,
  attribution_text   TEXT,
  rights_holder      TEXT,
  doi                TEXT,
  citation_text      TEXT,

  -- Docent search index tracking (Phase 1b populates).
  embedding_version  INTEGER,

  schema_version     INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL,

  -- Review-queue lifecycle (Phase 6 populates; all NULL otherwise).
  submitted_at       TEXT,
  approved_at        TEXT,
  rejected_at        TEXT,
  rejected_reason    TEXT,

  published_at       TEXT,
  retracted_at       TEXT,
  publisher_id       TEXT,
  FOREIGN KEY (publisher_id) REFERENCES publishers(id)
);

CREATE TABLE featured_datasets (
  dataset_id   TEXT PRIMARY KEY,
  position     INTEGER NOT NULL,             -- display order; lower = higher
  added_by     TEXT NOT NULL,                -- publishers.id
  added_at     TEXT NOT NULL,
  FOREIGN KEY (dataset_id) REFERENCES datasets(id) ON DELETE CASCADE,
  FOREIGN KEY (added_by)   REFERENCES publishers(id)
);

CREATE TABLE node_identity (
  node_id            TEXT PRIMARY KEY,        -- ULID, generated at install
  display_name       TEXT NOT NULL,
  base_url           TEXT NOT NULL,           -- https://terraviz.example.org
  description        TEXT,
  contact_email      TEXT,
  public_key         TEXT NOT NULL,           -- Ed25519, base64
  created_at         TEXT NOT NULL
);

CREATE TABLE publishers (
  id              TEXT PRIMARY KEY,           -- ULID
  email           TEXT NOT NULL UNIQUE,
  display_name    TEXT NOT NULL,
  affiliation     TEXT,
  org_id          TEXT,                       -- nullable; FK + orgs table arrive in Phase 6
  role            TEXT NOT NULL,              -- staff | community | readonly
  is_admin        INTEGER NOT NULL DEFAULT 0,
  status          TEXT NOT NULL,              -- pending | active | suspended
  created_at      TEXT NOT NULL
);

CREATE TABLE tour_dataset_refs (
  tour_id    TEXT NOT NULL,
  dataset_id TEXT NOT NULL,
  PRIMARY KEY (tour_id, dataset_id),
  FOREIGN KEY (tour_id) REFERENCES tours(id) ON DELETE CASCADE
);

CREATE TABLE tours (
  id                 TEXT PRIMARY KEY,
  slug               TEXT NOT NULL UNIQUE,
  origin_node        TEXT NOT NULL,
  title              TEXT NOT NULL,
  description        TEXT,
  tour_json_ref      TEXT NOT NULL,           -- r2:<key>
  thumbnail_ref      TEXT,
  visibility         TEXT NOT NULL DEFAULT 'public',
  schema_version     INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL,
  published_at       TEXT,
  publisher_id       TEXT,
  FOREIGN KEY (publisher_id) REFERENCES publishers(id)
);

-- Indexes

CREATE INDEX idx_asset_uploads_dataset ON asset_uploads(dataset_id, created_at);
CREATE INDEX idx_audit_subject ON audit_events(subject_kind, subject_id, created_at);
CREATE INDEX idx_datasets_publisher  ON datasets(publisher_id);
CREATE INDEX idx_datasets_updated_at ON datasets(updated_at);
CREATE INDEX idx_datasets_visibility ON datasets(visibility, is_hidden, retracted_at);
CREATE INDEX idx_featured_datasets_position ON featured_datasets(position);
CREATE INDEX idx_renditions_dataset ON dataset_renditions(dataset_id);
