/**
 * Shared `Env` type for catalog-backend Pages Functions.
 *
 * Bindings are declared in `wrangler.toml` and provisioned via the
 * Cloudflare Pages dashboard. Phase 1a uses two: D1 for the
 * catalog tables (CATALOG_DB) and KV for the hot-path snapshot
 * cache (CATALOG_KV). Later phases extend this surface with R2,
 * Stream, Queues, and Workers AI bindings — when they land, this
 * type grows additively.
 *
 * Every binding is optional in the type so Functions can degrade
 * gracefully when an operator forgot to wire one in the dashboard:
 * the catalog endpoint, for example, returns a 503 with a clear
 * "CATALOG_DB binding missing" body rather than crashing on a
 * type error against an undefined.
 */
export interface CatalogEnv {
  /** D1 database holding the catalog tables (Phase 1a +). */
  CATALOG_DB?: D1Database
  /** KV namespace caching the rendered catalog response. */
  CATALOG_KV?: KVNamespace
  /**
   * Override for the upstream Vimeo proxy used by the manifest
   * endpoint to resolve `vimeo:` `data_ref` values. Defaults to the
   * production proxy when unset; tests stub it via a mock fetch.
   * Phase 2 retires this field once Cloudflare Stream takes over
   * video hosting.
   */
  VIDEO_PROXY_BASE?: string
  /**
   * Ed25519 private key (single-line base64-DER PKCS8) used to sign
   * federation responses. Generated by `npm run gen:node-key`,
   * stored as a Wrangler secret in production. Phase 1a only reads
   * the corresponding public key (already persisted in
   * `node_identity.public_key`) — the private key sits unused until
   * the federation feed lands in Phase 4.
   */
  NODE_ID_PRIVATE_KEY_PEM?: string
  /**
   * Cloudflare Access team subdomain (e.g.
   * `zyra-project.cloudflareaccess.com`). The publisher-API
   * middleware fetches the team's JWKS from
   * `https://<team>/cdn-cgi/access/certs` to verify the
   * `Cf-Access-Jwt-Assertion` header on every request.
   */
  ACCESS_TEAM_DOMAIN?: string
  /**
   * Application audience tag (the hex string the Cloudflare
   * dashboard shows next to each Access Application). The middleware
   * rejects JWTs whose `aud` claim does not include this value, so
   * a token minted for a different application of the same team
   * cannot be replayed against `/api/v1/publish/**`.
   */
  ACCESS_AUD?: string
  /**
   * `"true"` skips Access verification in local dev and JIT-provisions
   * a staff publisher keyed off `DEV_PUBLISHER_EMAIL`. The middleware
   * refuses to honour this flag against a non-loopback hostname so a
   * misconfigured production deploy cannot accidentally open the
   * publisher API to the world.
   */
  DEV_BYPASS_ACCESS?: string
  /**
   * Email used by the dev-bypass JIT publisher row. Defaults to
   * `dev@localhost`. Stamping the operator's real email is handy
   * if you are testing publish-flow audit events locally and want
   * the rows attributed to the right human.
   */
  DEV_PUBLISHER_EMAIL?: string
  /**
   * HMAC-SHA-256 secret used to sign short-lived preview tokens
   * (`POST /api/v1/publish/datasets/{id}/preview`). Stored as a
   * Wrangler secret in production. Required: the preview endpoints
   * fail closed (503 `preview_unconfigured`) when this is unset
   * unless BOTH `DEV_BYPASS_ACCESS=true` AND
   * `ALLOW_DEV_PREVIEW_FALLBACK=true` are also set.
   */
  PREVIEW_SIGNING_KEY?: string
  /**
   * Belt-and-suspenders gate for the deterministic preview signing
   * fallback. The publish middleware refuses `DEV_BYPASS_ACCESS=true`
   * on a non-loopback hostname, but the anonymous preview consumer
   * lives outside that middleware. Requiring this second flag keeps
   * a production misconfig (someone forgets to remove
   * `DEV_BYPASS_ACCESS=true`) from accidentally accepting forged
   * preview tokens.
   */
  ALLOW_DEV_PREVIEW_FALLBACK?: string
}
