/**
 * Shared `Env` type for catalog-backend Pages Functions.
 *
 * Bindings are declared in `wrangler.toml` and provisioned via the
 * Cloudflare Pages dashboard. Phase 1a uses two: D1 for the
 * catalog tables (CATALOG_DB) and KV for the hot-path snapshot
 * cache (CATALOG_KV). Later phases extend this surface with R2,
 * Stream, Queues, and Workers AI bindings — when they land, this
 * type grows additively.
 *
 * Every binding is optional in the type so Functions can degrade
 * gracefully when an operator forgot to wire one in the dashboard:
 * the catalog endpoint, for example, returns a 503 with a clear
 * "CATALOG_DB binding missing" body rather than crashing on a
 * type error against an undefined.
 */
export interface CatalogEnv {
  /** D1 database holding the catalog tables (Phase 1a +). */
  CATALOG_DB?: D1Database
  /** KV namespace caching the rendered catalog response. */
  CATALOG_KV?: KVNamespace
  /**
   * Override for the upstream Vimeo proxy used by the manifest
   * endpoint to resolve `vimeo:` `data_ref` values. Defaults to the
   * production proxy when unset; tests stub it via a mock fetch.
   * Phase 2 retires this field once Cloudflare Stream takes over
   * video hosting.
   */
  VIDEO_PROXY_BASE?: string
  /**
   * Ed25519 private key (single-line base64-DER PKCS8) used to sign
   * federation responses. Generated by `npm run gen:node-key`,
   * stored as a Wrangler secret in production. Phase 1a only reads
   * the corresponding public key (already persisted in
   * `node_identity.public_key`) — the private key sits unused until
   * the federation feed lands in Phase 4.
   */
  NODE_ID_PRIVATE_KEY_PEM?: string
  /**
   * Cloudflare Access team subdomain (e.g.
   * `zyra-project.cloudflareaccess.com`). The publisher-API
   * middleware fetches the team's JWKS from
   * `https://<team>/cdn-cgi/access/certs` to verify the
   * `Cf-Access-Jwt-Assertion` header on every request.
   */
  ACCESS_TEAM_DOMAIN?: string
  /**
   * Application audience tag (the hex string the Cloudflare
   * dashboard shows next to each Access Application). The middleware
   * rejects JWTs whose `aud` claim does not include this value, so
   * a token minted for a different application of the same team
   * cannot be replayed against `/api/v1/publish/**`.
   */
  ACCESS_AUD?: string
  /**
   * `"true"` skips Access verification in local dev and JIT-provisions
   * a staff publisher keyed off `DEV_PUBLISHER_EMAIL`. The middleware
   * refuses to honour this flag against a non-loopback hostname so a
   * misconfigured production deploy cannot accidentally open the
   * publisher API to the world.
   */
  DEV_BYPASS_ACCESS?: string
  /**
   * Email used by the dev-bypass JIT publisher row. Defaults to
   * `dev@localhost`. Stamping the operator's real email is handy
   * if you are testing publish-flow audit events locally and want
   * the rows attributed to the right human.
   */
  DEV_PUBLISHER_EMAIL?: string
  /**
   * HMAC-SHA-256 secret used to sign short-lived preview tokens
   * (`POST /api/v1/publish/datasets/{id}/preview`). Stored as a
   * Wrangler secret in production. Required: the preview endpoints
   * fail closed (503 `preview_unconfigured`) when this is unset
   * unless BOTH `DEV_BYPASS_ACCESS=true` AND
   * `ALLOW_DEV_PREVIEW_FALLBACK=true` are also set.
   */
  PREVIEW_SIGNING_KEY?: string
  /**
   * Belt-and-suspenders gate for the deterministic preview signing
   * fallback. The publish middleware refuses `DEV_BYPASS_ACCESS=true`
   * on a non-loopback hostname, but the anonymous preview consumer
   * lives outside that middleware. Requiring this second flag keeps
   * a production misconfig (someone forgets to remove
   * `DEV_BYPASS_ACCESS=true`) from accidentally accepting forged
   * preview tokens.
   */
  ALLOW_DEV_PREVIEW_FALLBACK?: string
  /**
   * R2 bucket binding for catalog assets — sphere thumbnails,
   * non-Stream image data, legends, captions, tour JSON. The
   * binding is what the asset-complete handler uses to read
   * just-uploaded bytes and verify `content_digest` (Phase 1b).
   * Wrangler provisions a local on-disk emulation under
   * `.wrangler/state/v3/r2/` even without real credentials.
   */
  CATALOG_R2?: R2Bucket
  /**
   * Bucket name as configured in the R2 dashboard. Defaults to
   * `terraviz-assets` (the canonical name in
   * `CATALOG_ASSETS_PIPELINE.md`); override only if a fork picks
   * a different name. Used to build the SigV4 host for presigned
   * PUT URLs.
   */
  CATALOG_R2_BUCKET?: string
  /**
   * R2 S3-compatible endpoint, e.g.
   * `https://<account>.r2.cloudflarestorage.com`. Required for
   * presigned-PUT minting; the dashboard prints it on the bucket
   * page. Local dev with `MOCK_R2=true` does not need it.
   */
  R2_S3_ENDPOINT?: string
  /** R2 S3 access-key id. Cloudflare dashboard → R2 → Manage API tokens. */
  R2_ACCESS_KEY_ID?: string
  /** R2 S3 secret access key — Wrangler secret in production. */
  R2_SECRET_ACCESS_KEY?: string
  /**
   * Public-readable origin for the R2 bucket — e.g.
   * `https://assets.terraviz.example.com` for a custom-domain
   * mapping, or the bucket's public-access URL. Used by the
   * manifest endpoint to construct image/file URLs that the
   * frontend can fetch unauthenticated. When unset, the manifest
   * falls back to MOCK_R2 (dev) or the S3 endpoint
   * (public buckets). Restricted-bucket presigned-GET semantics
   * land in Phase 4 federation work.
   */
  R2_PUBLIC_BASE?: string
  /**
   * `"true"` makes the asset-init handler emit deterministic
   * `https://mock-r2.localhost/...` URLs instead of real presigned
   * ones, so the contributor walkthrough works without an R2 S3
   * token. Because no bytes are actually uploaded to that mock URL,
   * `/asset/{upload_id}/complete` skips the binding-based digest
   * verification and trusts the publisher's claimed digest as
   * ground truth (parallel to the Stream-mock behaviour). The
   * `mock_r2_unsafe` 500 refusal on non-loopback hostnames keeps a
   * production misconfig from accepting forged claims.
   */
  MOCK_R2?: string
  /**
   * Cloudflare account id that owns the Stream subscription.
   * Required for the video upload + transcode-status endpoints
   * (Phase 1b). Local dev with `MOCK_STREAM=true` does not need it.
   */
  STREAM_ACCOUNT_ID?: string
  /**
   * Stream API token (`Stream: Edit` permission). Wrangler secret
   * in production. Local dev with `MOCK_STREAM=true` does not
   * need it.
   */
  STREAM_API_TOKEN?: string
  /**
   * Customer subdomain printed in the Stream dashboard, e.g.
   * `customer-abc123.cloudflarestream.com`. Used to build the
   * public HLS playback URL the manifest endpoint serves.
   */
  STREAM_CUSTOMER_SUBDOMAIN?: string
  /**
   * `"true"` makes the Stream helpers return deterministic stub
   * upload URLs / uids / transcode statuses so the contributor
   * walkthrough works without a Cloudflare Stream subscription.
   */
  MOCK_STREAM?: string
  /**
   * Origin used by the sphere-thumbnail generation pipeline to
   * issue Cloudflare Images URL transformations against image
   * datasets (Phase 1b). When set, image-source thumbnails are
   * resized via `${CF_IMAGES_RESIZE_BASE}/cdn-cgi/image/fit=fill,...`.
   * When unset, the job falls back to the source bytes (the
   * publisher portal's regenerate button (Phase 3) handles the
   * unrepresentative case manually). Stream-source thumbnails
   * always go through Stream's own thumbnail API and never consult
   * this var.
   */
  CF_IMAGES_RESIZE_BASE?: string
}
