/**
 * Helpers shared between `dump-catalog-schema.ts` and the migration
 * smoke test. Centralising "where the migrations live" and "how to
 * apply them to an in-memory DB" guarantees the dump and the test
 * see byte-identical SQL.
 *
 * Wrangler's D1 migration runner strips inline `-- comment` text
 * before submitting CREATE statements to SQLite, while `db.exec()`
 * preserves them in `sqlite_master.sql`. We standardise on the
 * `db.exec()` path because it works without Wrangler — contributors
 * running the test or the dump don't need a local D1 in
 * `.wrangler/`. The on-disk Wrangler D1 file is therefore *not* the
 * canonical schema source; the migrations on disk are.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import Database from 'better-sqlite3'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '../..')

export const MIGRATIONS_DIR = resolve(REPO_ROOT, 'migrations/catalog')
export const SCHEMA_SNAPSHOT_PATH = resolve(REPO_ROOT, 'migrations/catalog-schema.sql')

export function listMigrations(): string[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter(name => /^\d{4}_.+\.sql$/.test(name))
    .sort()
}

/** Apply every Phase-1a migration in order to the given SQLite handle. */
export function applyMigrations(db: Database.Database): void {
  for (const name of listMigrations()) {
    const sql = readFileSync(join(MIGRATIONS_DIR, name), 'utf-8')
    db.exec(sql)
  }
}

/** Build a fresh in-memory DB with all migrations applied. */
export function freshMigratedDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  applyMigrations(db)
  return db
}

export const SCHEMA_HEADER = `-- migrations/catalog-schema.sql — post-migration snapshot.
--
-- Auto-generated by \`npm run db:dump-schema\` from a fresh
-- in-memory apply of every migration under migrations/catalog/.
-- CI runs the migrations smoke test and fails the PR if the
-- generated output drifts from this file.
--
-- Do not edit by hand. Edit the migration file in
-- migrations/catalog/ and regenerate.
`

/** Render the schema-snapshot text from the given DB. */
export function renderSchemaSnapshot(db: Database.Database): string {
  const tableRows = db
    .prepare(
      `SELECT sql FROM sqlite_master
       WHERE type='table' AND name NOT LIKE 'sqlite_%'
         AND sql IS NOT NULL
       ORDER BY name`,
    )
    .all() as Array<{ sql: string }>
  const indexRows = db
    .prepare(
      `SELECT sql FROM sqlite_master
       WHERE type='index' AND sql IS NOT NULL
       ORDER BY name`,
    )
    .all() as Array<{ sql: string }>

  return (
    SCHEMA_HEADER +
    '\n-- Tables\n\n' +
    tableRows.map(r => r.sql.trim() + ';').join('\n\n') +
    '\n\n-- Indexes\n\n' +
    indexRows.map(r => r.sql.trim() + ';').join('\n') +
    '\n'
  )
}
