/**
 * scripts/read-penpot.ts — Channel-A reverse exporter (Penpot → JSON).
 *
 * The mirror of the three `sync-penpot-*.ts` seeders, run in the read
 * direction. Where each seeder emits *writer* plugin JS that upserts
 * tokens into Penpot via the MCP `execute_code` tool, this emits a
 * single *reader* plugin JS that dumps the entire local token graph —
 * every set, every token, every theme — back out as JSON.
 *
 * One reader, not three. The seeders are split by concern (global /
 * components / modes) because their *write* plans differ. Reading is
 * uniform: `penpot.library.local.tokens` is a single object graph, and
 * the reverse reconcile (`penpot-reconcile.ts`) needs the whole graph
 * at once anyway — mode overrides live in separate `Modes/*` sets that
 * must be folded back under the base tokens. So a single pass that reads
 * all seeded sets (Global + Components/* + Modes/*) is the faithful
 * mirror of "all the seeders", and avoids three readers redundantly
 * walking the same graph. (`docs/DESIGN_SYNC_PLAN.md` R1 allows either a
 * per-seeder `read-penpot-*.ts` or "a --read mode on the existing
 * script"; this unified reader is the cleaner shape.)
 *
 * The emitted JS returns a `PenpotGraph` (see `penpot-reconcile.ts`),
 * which the reconcile step consumes directly. It is read-only: it never
 * calls `addSet` / `addToken` / `toggleActive`, so it is safe to run
 * against the live design file.
 *
 * File guard. Like the seeders' operating note, the reader guards on
 * `penpot.currentFile?.name` so a wrong focused file is caught before
 * its tokens are mistaken for the design system's. When a guard name is
 * baked in (the default), a mismatch returns `{ error, expected, actual }`
 * instead of a graph; pass `null` to skip the guard.
 *
 * CLI:
 *   npx tsx scripts/read-penpot.ts            # print reader plugin code
 *   npx tsx scripts/read-penpot.ts --list     # print emitted code metadata
 */

import { isInvokedAsScript } from './lib/cli.ts'
import type { PenpotGraph } from './penpot-reconcile.ts'

export type { PenpotGraph }

/**
 * The Penpot library file the seeders target (see the header comment in
 * each `sync-penpot-*.ts`). Used as the default reader file guard.
 */
export const DESIGN_FILE_NAME = 'TerraViz - Design System'

/**
 * Build the read-only reader plugin JS. `expectedFile` guards on the
 * focused file name; pass `null` to read whatever file is focused.
 */
export function buildReaderCode(expectedFile: string | null = DESIGN_FILE_NAME): string {
  const guard =
    expectedFile === null
      ? ''
      : `
const expected = ${JSON.stringify(expectedFile)};
const actual = penpot.currentFile ? penpot.currentFile.name : null;
if (actual !== expected) {
  return { error: 'wrong focused file', expected, actual };
}
`
  return `// Generated by scripts/read-penpot.ts — READ-ONLY dump of the local
// Penpot token graph. Run via the MCP execute_code tool against the
// TerraViz - Design System file. Returns a PenpotGraph for the reverse
// reconcile (scripts/penpot-reconcile.ts). Performs no writes.
const tokens = penpot.library.local.tokens;
${guard}const sets = tokens.sets.map(s => ({
  name: s.name,
  tokens: s.tokens.map(t => ({
    name: t.name,
    type: t.type,
    value: t.value,
    description: t.description || undefined,
  })),
}));
const themes = tokens.themes.map(t => ({
  group: t.group,
  name: t.name,
  activeSets: t.activeSets.map(s => s.name),
}));
return {
  file: penpot.currentFile ? penpot.currentFile.name : null,
  sets,
  themes,
};
`
}

if (isInvokedAsScript(import.meta.url)) {
  const arg = process.argv[2]
  if (arg === '--list') {
    const code = buildReaderCode()
    process.stdout.write(
      JSON.stringify(
        { file: DESIGN_FILE_NAME, bytes: code.length, lines: code.split('\n').length },
        null,
        2,
      ) + '\n',
    )
  } else if (arg && arg !== '--code') {
    process.stderr.write(`unknown arg: ${arg}\nusage: read-penpot.ts [--code | --list]\n`)
    process.exit(2)
  } else {
    process.stdout.write(buildReaderCode())
  }
}
