// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Zyra Project

/**
 * scripts/sync-penpot-global.ts — Penpot Global token-set seeder.
 *
 * Reads `tokens/global.json` (W3C Design Tokens) and produces:
 *   1. A flat list of `{ name, type, value, description? }` specs
 *      (`buildGlobalTokenSpecs`), where `name` mirrors the JSON path
 *      (`color.accent`, `radius.md`, `accent-opacity.o05`).
 *   2. A self-contained JS string (`buildPluginCode`) ready to send
 *      via the Penpot MCP `execute_code` tool. Running it in the
 *      plugin context idempotently upserts each spec into a single
 *      token set named "Global": creates if missing, updates only
 *      when the value differs, leaves unchanged ones alone, and
 *      reports any tokens already in the set that have no JSON
 *      counterpart (orphans) without deleting them.
 *
 * The JSON file is the source of truth for both `tokens.css` (via
 * Style Dictionary) and Penpot, so the seeded values must match
 * exactly. This pass intentionally skips mode overrides
 * (`com.tokens-studio.modes`) — see Phase 3 in
 * `docs/DESIGN_SYSTEM_PLAN.md` for the staged scope.
 *
 * CLI:
 *   npx tsx scripts/sync-penpot-global.ts            # print plugin code
 *   npx tsx scripts/sync-penpot-global.ts --list     # print specs as JSON
 */

import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { isInvokedAsScript } from './lib/cli.ts'

export type PenpotTokenType = 'color' | 'dimension'

export interface TokenSpec {
  name: string
  type: PenpotTokenType
  value: string
  description?: string
}

export interface SkippedToken {
  path: string
  reason: string
}

export interface BuildSpecsResult {
  specs: TokenSpec[]
  skipped: SkippedToken[]
}

interface W3CTokenLike {
  $value: unknown
  $type: unknown
  $description?: unknown
}

export const GLOBAL_SET_NAME = 'Global'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')
const GLOBAL_TOKENS_PATH = resolve(REPO_ROOT, 'tokens/global.json')

export function readGlobalTokensJson(): unknown {
  return JSON.parse(readFileSync(GLOBAL_TOKENS_PATH, 'utf-8'))
}

export function buildGlobalTokenSpecs(json: unknown = readGlobalTokensJson()): BuildSpecsResult {
  const specs: TokenSpec[] = []
  const skipped: SkippedToken[] = []
  walk(json, [], specs, skipped)
  return { specs, skipped }
}

function walk(
  node: unknown,
  path: string[],
  specs: TokenSpec[],
  skipped: SkippedToken[],
) {
  if (!isPlainObject(node)) return
  if (looksLikeW3CToken(node)) {
    const joined = path.join('.')
    const t = node.$type
    if (t !== 'color' && t !== 'dimension') {
      skipped.push({ path: joined, reason: `unsupported $type "${String(t)}"` })
      return
    }
    if (typeof node.$value !== 'string') {
      skipped.push({ path: joined, reason: 'non-string $value' })
      return
    }
    const spec: TokenSpec = { name: joined, type: t, value: node.$value }
    if (typeof node.$description === 'string' && node.$description.length > 0) {
      spec.description = node.$description
    }
    specs.push(spec)
    return
  }
  for (const key of Object.keys(node)) {
    walk(node[key], [...path, key], specs, skipped)
  }
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function looksLikeW3CToken(node: Record<string, unknown>): node is W3CTokenLike & Record<string, unknown> {
  return '$value' in node && '$type' in node
}

export function buildPluginCode(specs: TokenSpec[], setName: string = GLOBAL_SET_NAME): string {
  const payload = JSON.stringify({ setName, specs }, null, 2)
  return `// Generated by scripts/sync-penpot-global.ts — idempotent seed for the
// Penpot "${setName}" token set. Run via the MCP execute_code tool against
// the TerraViz - Design System file.
const PLAN = ${payload};
const tokens = penpot.library.local.tokens;
let set = tokens.sets.find(s => s.name === PLAN.setName);
if (!set) set = tokens.addSet({ name: PLAN.setName });
if (!set.active) set.toggleActive();
const existing = new Map(set.tokens.map(t => [t.name, t]));
const created = [], updated = [], unchanged = [], typeMismatches = [];
for (const spec of PLAN.specs) {
  let token;
  const prev = existing.get(spec.name);
  if (!prev) {
    token = set.addToken({ type: spec.type, name: spec.name, value: spec.value });
    created.push(spec.name);
  } else if (prev.type !== spec.type) {
    typeMismatches.push({ name: spec.name, want: spec.type, got: prev.type });
    continue;
  } else {
    token = prev;
    if (token.value !== spec.value) {
      token.value = spec.value;
      updated.push(spec.name);
    } else {
      unchanged.push(spec.name);
    }
  }
  const desc = spec.description || '';
  if ((token.description || '') !== desc) token.description = desc;
}
const specNames = new Set(PLAN.specs.map(s => s.name));
const orphans = set.tokens.filter(t => !specNames.has(t.name)).map(t => t.name);
return {
  setName: PLAN.setName,
  totals: {
    specs: PLAN.specs.length,
    created: created.length,
    updated: updated.length,
    unchanged: unchanged.length,
    orphans: orphans.length,
    typeMismatches: typeMismatches.length,
  },
  created, updated, unchanged, orphans, typeMismatches,
};
`
}

if (isInvokedAsScript(import.meta.url)) {
  const arg = process.argv[2]
  const { specs, skipped } = buildGlobalTokenSpecs()
  for (const s of skipped) {
    process.stderr.write(`[sync-penpot-global] skipped ${s.path}: ${s.reason}\n`)
  }
  if (arg === '--list') {
    process.stdout.write(JSON.stringify(specs, null, 2) + '\n')
  } else if (arg && arg !== '--code') {
    process.stderr.write(`unknown arg: ${arg}\nusage: sync-penpot-global.ts [--code | --list]\n`)
    process.exit(2)
  } else {
    process.stdout.write(buildPluginCode(specs))
  }
}
